### ISSUE TITLE
ImportError: No module named util

### ISSUE THREAD

**Issue by Cuinnton** [miked63017/dinolite_uvc_led_control#6]
Not sure how to successfully install. I have v4l-utilsand and libwebcam-0.2.5 with uvcdynctrl.
```
pi@raspberry:~/dinolite_uvc_led_control-master $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
```
The error I get:
```
pi@raspberry:~/dinolite_uvc_led_control-master $ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to dinoliteuvccontrol.egg-info/requires.txt
writing dinoliteuvccontrol.egg-info/PKG-INFO
writing top-level names to dinoliteuvccontrol.egg-info/top_level.txt
writing dependency_links to dinoliteuvccontrol.egg-info/dependency_links.txt
reading manifest file 'dinoliteuvccontrol.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dinoliteuvccontrol.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/dinoliteuvccontrol
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/dinoliteuvccontrol.py -> build/bdist.linux-i686/egg/dinoliteuvccontrol
creating build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/devices/device0890.json -> build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/devices/device0980.json -> build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/devices/device0980.py -> build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/devices/device0890.py -> build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/devices/__init__.py -> build/bdist.linux-i686/egg/dinoliteuvccontrol/devices
copying build/lib.linux-i686-2.7/dinoliteuvccontrol/__init__.py -> build/bdist.linux-i686/egg/dinoliteuvccontrol
byte-compiling build/bdist.linux-i686/egg/dinoliteuvccontrol/dinoliteuvccontrol.py to dinoliteuvccontrol.pyc
byte-compiling build/bdist.linux-i686/egg/dinoliteuvccontrol/devices/device0980.py to device0980.pyc
byte-compiling build/bdist.linux-i686/egg/dinoliteuvccontrol/devices/device0890.py to device0890.pyc
byte-compiling build/bdist.linux-i686/egg/dinoliteuvccontrol/devices/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-i686/egg/dinoliteuvccontrol/__init__.py to __init__.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
installing scripts to build/bdist.linux-i686/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-i686/egg/EGG-INFO/scripts
copying build/scripts-2.7/dinolite -> build/bdist.linux-i686/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-i686/egg/EGG-INFO/scripts/dinolite to 755
copying dinoliteuvccontrol.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying dinoliteuvccontrol.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying dinoliteuvccontrol.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying dinoliteuvccontrol.egg-info/requires.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying dinoliteuvccontrol.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
dinoliteuvccontrol.devices.device0890: module references __file__
dinoliteuvccontrol.devices.device0980: module references __file__
creating 'dist/dinoliteuvccontrol-0.0.1-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing dinoliteuvccontrol-0.0.1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/dinoliteuvccontrol-0.0.1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/dinoliteuvccontrol-0.0.1-py2.7.egg
Extracting dinoliteuvccontrol-0.0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
dinoliteuvccontrol 0.0.1 is already the active version in easy-install.pth
Installing dinolite script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/dinoliteuvccontrol-0.0.1-py2.7.egg
Processing dependencies for dinoliteuvccontrol==0.0.1
Searching for soupsieve>1.2
Reading https://pypi.org/simple/soupsieve/
Downloading https://files.pythonhosted.org/packages/3e/db/5ba900920642414333bdc3cb397075381d63eafc7e75c2373bbc560a9fa1/soupsieve-2.0.1.tar.gz#sha256=a59dc181727e95d25f781f0eb4fd1825ff45590ec8ff49eadfd7f1a537cc0232
Best match: soupsieve 2.0.1
Processing soupsieve-2.0.1.tar.gz
Writing /tmp/easy_install-OLPrsd/soupsieve-2.0.1/setup.cfg
Running soupsieve-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-OLPrsd/soupsieve-2.0.1/egg-dist-tmp-us25WJ
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    'scripts/dinolite'
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 443, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 732, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 777, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-OLPrsd/soupsieve-2.0.1/setup.py", line 40, in <module>
    
  File "/tmp/easy_install-OLPrsd/soupsieve-2.0.1/setup.py", line 11, in get_version
    with open(os.path.join(dirname, 'requirements.txt'), 'r') as f:
ImportError: No module named util
```

**Comment by Cuinnton** [comment]
Ah made it install by using Python 3 on the Raspberry Pi `sudo python3 setup.py install
`
